[rtpengine]
table = -1
interface = 204.168.137.104
endpoint-learning = immediate
listen-ng = 127.0.0.1:22222
port-min = 30000
port-max = 31000
timeout = 60
silent-timeout = 600
delete-delay = 30
foreground = true
log-stderr = true
