import type { PlatformTenantView } from '@/lib/utils/platform';
import { defaultFeatures } from '@/lib/utils/platform';

export const DEMO_PLATFORM_TENANTS: PlatformTenantView[] = [
  {
    id: '1',
    slug: 'labbik-telecom',
    name: 'LABBIK Telecom',
    domain: 'labbik.blinkone.local',
    plan: 'enterprise',
    status: 'active',
    agentCount: 42,
    createdAt: '2025-01-15T00:00:00Z',
    location: 'Muscat, OM',
    features: defaultFeatures({
      pstn: true,
      whatsappCalling: true,
      aiAssist: true,
      ivr: true,
      sla: true,
      voiceBot: false,
      rag: true,
      billing: true,
      telephony: true,
    }),
  },
  {
    id: '2',
    slug: 'gulf-retail',
    name: 'Gulf Retail Group',
    domain: 'gulf-retail.blinkone.local',
    plan: 'pro',
    status: 'active',
    agentCount: 18,
    createdAt: '2025-06-01T00:00:00Z',
    location: 'Dubai, AE',
    features: defaultFeatures({
      pstn: true,
      whatsappCalling: true,
      aiAssist: true,
      ivr: false,
      sla: true,
      voiceBot: false,
      rag: true,
      billing: true,
    }),
  },
  {
    id: '3',
    slug: 'oman-startup',
    name: 'Oman Startup Hub',
    domain: 'startup.blinkone.local',
    plan: 'starter',
    status: 'trial',
    agentCount: 5,
    createdAt: '2026-04-01T00:00:00Z',
    location: 'Salalah, OM',
    features: defaultFeatures({
      pstn: false,
      whatsappCalling: true,
      aiAssist: false,
      ivr: false,
      sla: false,
      voiceBot: false,
      rag: false,
      billing: false,
    }),
  },
  {
    id: '4',
    slug: 'legacy-corp',
    name: 'Legacy Corp (suspended)',
    domain: 'legacy.blinkone.local',
    plan: 'pro',
    status: 'suspended',
    agentCount: 0,
    createdAt: '2024-11-20T00:00:00Z',
    location: 'Muscat, OM',
    features: defaultFeatures({
      pstn: true,
      whatsappCalling: false,
      aiAssist: false,
      ivr: true,
      sla: true,
      voiceBot: false,
      rag: false,
      billing: true,
    }),
  },
];
