/**
 * Demo fixtures for Sprint 3 N1 — outbound webhook management.
 */

import type { WebhookEndpoint, WebhookDelivery } from '@/lib/api/webhooks';

export const DEMO_WEBHOOK_ENDPOINTS: WebhookEndpoint[] = [
  {
    id: 'ep-001',
    tenantId: '1',
    name: 'CRM Sync',
    url: 'https://crm.acme.example/blinkone/webhook',
    eventsSubscribed: ['conversation.created', 'conversation.resolved', 'message.created'],
    enabled: true,
    extraHeaders: {},
    createdAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'ep-002',
    tenantId: '1',
    name: 'Slack Alerts',
    url: 'https://hooks.slack.com/services/T000/B000/xxxxx',
    eventsSubscribed: ['sla.breached'],
    enabled: true,
    extraHeaders: {},
    createdAt: '2026-05-01T09:30:00Z',
  },
  {
    id: 'ep-003',
    tenantId: '1',
    name: 'Legacy analytics (disabled)',
    url: 'https://analytics.legacy.example/events',
    eventsSubscribed: ['*'],
    enabled: false,
    extraHeaders: { 'X-Api-Key': 'redacted' },
    createdAt: '2025-12-01T00:00:00Z',
  },
];

export const DEMO_WEBHOOK_DELIVERIES: WebhookDelivery[] = [
  {
    id: 'del-001',
    endpointId: 'ep-001',
    tenantId: '1',
    eventId: 'evt-aaa',
    eventType: 'conversation.created',
    attempt: 1,
    status: 'succeeded',
    responseStatus: 200,
    responseBodyTruncated: '{"ok":true}',
    attemptedAt: '2026-05-27T10:31:00Z',
    nextRetryAt: null,
    createdAt: '2026-05-27T10:31:00Z',
  },
  {
    id: 'del-002',
    endpointId: 'ep-001',
    tenantId: '1',
    eventId: 'evt-bbb',
    eventType: 'message.created',
    attempt: 1,
    status: 'succeeded',
    responseStatus: 200,
    responseBodyTruncated: '{"ok":true}',
    attemptedAt: '2026-05-27T10:15:00Z',
    nextRetryAt: null,
    createdAt: '2026-05-27T10:15:00Z',
  },
  {
    id: 'del-003',
    endpointId: 'ep-002',
    tenantId: '1',
    eventId: 'evt-ccc',
    eventType: 'sla.breached',
    attempt: 2,
    status: 'failed',
    responseStatus: 503,
    responseBodyTruncated: 'Service Unavailable',
    attemptedAt: '2026-05-27T09:45:00Z',
    nextRetryAt: '2026-05-27T10:45:00Z',
    createdAt: '2026-05-27T09:40:00Z',
  },
  {
    id: 'del-004',
    endpointId: 'ep-001',
    tenantId: '1',
    eventId: 'evt-ddd',
    eventType: 'conversation.resolved',
    attempt: 6,
    status: 'dead',
    responseStatus: 404,
    responseBodyTruncated: 'Not Found',
    attemptedAt: '2026-05-26T18:00:00Z',
    nextRetryAt: null,
    createdAt: '2026-05-26T17:30:00Z',
  },
  {
    id: 'del-005',
    endpointId: 'ep-001',
    tenantId: '1',
    eventId: 'evt-eee',
    eventType: 'integration.test',
    attempt: 1,
    status: 'succeeded',
    responseStatus: 200,
    responseBodyTruncated: '{"ok":true}',
    attemptedAt: '2026-05-27T08:00:00Z',
    nextRetryAt: null,
    createdAt: '2026-05-27T08:00:00Z',
  },
];
